name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y gcc-m68k-linux-gnu
    - name: Build
      run: bash build.sh m68k-linux-gnu
    - name: Verify existence of floppy
      run: stat floppy.img
